// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations must use the unpooled endpoint: Neon's pooler (PgBouncer)
    // cannot hold the session state that DDL and advisory locks require.
    url: process.env["DIRECT_URL"],
  },
})
